### PR TITLE
Serve file directly for curl and wget user agents

### LINKED ISSUE #127: Consider returning the file directly without the /selif/ if a curl / wget useragent is detected

### PR DESCRIPTION
**Pull request by Thor77**
Fix #127

### CODE REVIEW

**Comment by andreimarcu** [comment]
Hi @Thor77, thanks for the PR. Can we have a config flag to disable it? I think it's a good default though

**Comment by Thor77** [comment]
Yeah, that's a good idea.
What should the config flag be called?

**Comment by Thor77** [comment]
Uhm, tests are not run by travis, are they? Is there a reason for that?

**Comment by hansenchris** [comment]
Something like -nodirectcurl ? Or something more generic if we expand the list of user agents later, -nodirectagents

**Comment by andreimarcu** [comment]
Something like -nodirectcurl ? Or something more generic if we expand the list of user agents later, -nodirectagents

**Comment by Thor77** [comment]
Added a flag and fixed the tests for Go 1.5 :)

**Comment by andreimarcu** [comment]
Thanks!

**Pull request merged**
