### PR TITLE
Make the web page mobile friendly

### PR DESCRIPTION
**Pull request by ssimono**
Hello, I noticed that the upload page is zoomed out on mobile and I was able to make it nicer with minimal changes that don't affect the wider screens (desktop) appearance.

| Before | After |
|----------|--------|
| before | after |

### CODE REVIEW

**Comment by andreimarcu** [comment]
Hey, thanks for the PR! 

There's a few things I noticed:

- The Randomize filename and File expiry texts are too close to each other and misaligned 
- A lot of the other pages render poorly with this:

chrome_2018-06-09_14-04-35
chrome_2018-06-09_14-04-58
chrome_2018-06-09_14-05-09
chrome_2018-06-09_14-05-29

**Comment by ssimono** [comment]
Hello, thanks for your nice feedback!

I am working on the issues you pointed and should amend this PR very soon

**Comment by ssimono** [comment]
Hello @andreimarcu, I made some changes mostly in the css and all the pages should now appear nicely on mobile and still nice as well on wider screens.

Feel free to have a look

**Comment by andreimarcu** [comment]
@ssimono I know it's been a while but if you're still interested in merging this there's one little nit about the placeholder text for the inputs that gets cut

i57xgkw6

**Comment by andreimarcu** [comment]
I pulled in your commits, thanks for working on this

**Comment by ssimono** [comment]
Thanks! Have a great day

**Pull request closed without merging**
