### PR TITLE
Add linx-cleanup tool

### LINKED ISSUE #116: Automatically delete outdated files
It would be great if Linx will check all the saved files and delete old files every couple of hours.

Now the files are deleted only when trying to download them.

### PR DESCRIPTION
**Pull request by mutantmonkey**
This doesn't completely fix #116, but it makes setting up a cron job to do cleanup much more pleasant.

I also dropped mercurial from the Dockerfile since it isn't needed anymore.

### CODE REVIEW

**Comment by andreimarcu** [comment]
Thank you!

**Comment by indrora** [comment]
for what it's worth, there is no copy of this built in the releases page.

**Comment by andreimarcu** [comment]
@indrora Thanks for noticing, I updated the build script and the release

**Comment by draft1** [comment]
Hi, does this support a separate config file? or options are needed to be as one line command?
Thanks.

**Pull request merged**
