### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Seb3thehacker**
I am actively maintaining a repo here:
https://github.com/Seb3thehacker/linx-server/tree/master

### CODE REVIEW

**Comment by andreimarcu** [comment]
Can you add your repo to the list of forks?

**Comment by Seb3thehacker** [comment]
It looks like it shows up as a fork here: https://github.com/andreimarcu/linx-server/network/members

**Comment by andreimarcu** [comment]
I meant like on line 7 of the readme

**Comment by Seb3thehacker** [comment]
Yeah

**Pull request closed without merging**
